---
- name: Check if systemd timer definition is present
  stat:
    path: '/etc/systemd/system/build-{{ beacon_node_service_name}}.timer'
  register: systemd_service_build_timer

- name: Check if the service is running
  systemd_service:
    name: 'build-{{ beacon_node_service_name }}.timer'
    state: 'stopped'
    enabled: false
  when: systemd_service_build_timer.stat.exists

# Allow to run the beacon node if the binary is build from source.
# This can fail since build script no longer symlinks in the build dir.
- name: Create a symlink with the build binary
  ignore_errors: true
  file:
    src: '{{ beacon_node_repo_path }}/build/nimbus_beacon_node'
    dest: '{{ beacon_node_bin_path }}/nimbus_beacon_node'
    state: link
  when: beacon_node_update_build 

- name: Remove build service, timer and consul definition
  file:
    path: '{{ item }}'
    state: absent
  with_items:
      - '/etc/systemd/system/build-{{ beacon_node_service_name }}.service'
      - '/etc/systemd/system/build-{{ beacon_node_service_name }}.timer'
      - '/etc/consul/service_build_{{ beacon_node_consul_service_file_name }}_timer.json'

- name: Reload systemctl services
  systemd_service:
    daemon_reload: true

- name: Restart Consul service
  systemd:
    name: consul.service
    state: reloaded
