---
- name: Create service directory
  file:
    path:    '{{ beacon_node_service_path }}'
    owner:   '{{ beacon_node_user }}'
    group:   '{{ beacon_node_group }}'
    state:   'directory'
    mode:    0770

- name: Create data directory
  file:
    path:    '{{ beacon_node_data_path }}'
    owner:   '{{ beacon_node_user }}'
    group:   '{{ beacon_node_group }}'
    state:   'directory'
    mode:    0700

- name: Create ERA directory symlink
  when: |
    beacon_node_era_symlink_path is defined
    and beacon_node_era_symlink_path
  file:
    src:     '{{ beacon_node_era_symlink_path }}'
    dest:    '{{ beacon_node_era_dir_path }}'
    owner:   '{{ beacon_node_user }}'
    group:   '{{ beacon_node_group }}'
    state:   'link'
    mode:    0700

- name: Create netkey file (optional)
  when: beacon_node_netkey is defined
  copy:
    dest:    '{{ beacon_node_netkey_path }}'
    content: '{{ beacon_node_netkey }}'
    owner:   '{{ beacon_node_user }}'
    group:   '{{ beacon_node_group }}'
    mode:    0600

- name: Create JWT secret file (optional)
  when: beacon_node_web3_jwt_secret is defined
  copy:
    dest:    '{{ beacon_node_web3_jwt_secret_path }}'
    content: '{{ beacon_node_web3_jwt_secret }}'
    owner:   '{{ beacon_node_user }}'
    group:   '{{ beacon_node_group }}'
    mode:    0400

- name: Copy Ansible toggle script
  copy:
    src:     'ansible_toggle.sh'
    dest:    '{{ beacon_node_service_path }}/ansible_enabled.sh'
    owner:   '{{ beacon_node_user }}'
    group:   '{{ beacon_node_group }}'
    mode:    0750

- name: Create helper scripts
  template:
    src:     '{{ item }}'
    dest:    '{{ beacon_node_service_path }}/{{ item|basename|replace(".j2", "") }}'
    owner:   '{{ beacon_node_user }}'
    group:   '{{ beacon_node_group }}'
    mode:    0750
  with_fileglob:
    - 'templates/scripts/*'
