---
- name: Create service directory
  file:
    path: '{{ beacon_node_data_path }}'
    state: directory
    owner: '{{ beacon_node_user }}'
    group: '{{ beacon_node_group }}'
    mode: 0770

- name: Create netkey file (optional)
  copy:
    dest: '{{ beacon_node_netkey_path }}'
    content: '{{ beacon_node_netkey }}'
    owner: '{{ beacon_node_user }}'
    group: '{{ beacon_node_group }}'
    mode: 0600
  when: beacon_node_netkey is defined

- name: Create helper scripts
  template:
    src: '{{ item }}'
    dest: '{{ beacon_node_service_path }}/{{ item|basename|replace(".j2", "") }}'
    owner: '{{ beacon_node_user }}'
    group: '{{ beacon_node_group }}'
    mode: 0750
  with_fileglob:
    - 'templates/scripts/*'
