---
- name: 'Create Consul service definition'
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ beacon_node_consul_service_file_name }}'
    consul_default_success_before_passing:   '{{ beacon_node_consul_success_before_passing }}'
    consul_default_failures_before_warning:  '{{ beacon_node_consul_failures_before_warning }}'
    consul_default_failures_before_critical: '{{ beacon_node_consul_failures_before_critical }}'
    consul_services:
      - id:   '{{ beacon_node_service_name }}'
        name: '{{ beacon_node_consul_service_name }}'
        port: '{{ beacon_node_listening_port }}'
        address: '{{ beacon_node_public_address }}'
        tags: ['{{ env }}.{{ stage }}', 'beacon', 'nimbus']
        meta:
          timestamp: '{{ ansible_date_time.iso8601 }}'
          compiler:  '{{ beacon_node_ver.json.data.compiler              | default("unknown") }}'
          version:   '{{ beacon_node_ver.json.data.version.split("/")[1] | default("unknown") }}'
          enr:       '{{ beacon_node_id.json.data.enr                    | default("unknown") }}'
          p2p_addr:  '{{ beacon_node_id.json.data.p2p_addresses[0]       | default("unknown") }}'
          disc_addr: '{{ beacon_node_id.json.data.discovery_addresses[0] | default("unknown") }}'
        checks:
          - id:   '{{ beacon_node_service_name }}-health'
            type: 'http'
            http: 'http://localhost:{{ beacon_node_rest_port }}/eth/v1/node/version'

      - id:   '{{ beacon_node_service_name }}-metrics'
        name: '{{ beacon_node_consul_metrics_service_name }}'
        port: '{{ beacon_node_metrics_port }}'
        address: '{{ ansible_local.wireguard.vpn_ip }}'
        tags: ['{{ env }}.{{ stage }}', 'beacon', 'nimbus', 'metrics']
        meta:
          container: '{{ beacon_node_service_name }}'
        checks:
          - id:   '{{ beacon_node_service_name }}-metrics-health'
            type: 'http'
            http: 'http://localhost:{{ beacon_node_metrics_port }}/health'
