---
- name: Open node ports in NFTables
  include_role: name=infra-role-open-ports
  vars:
    open_ports_list:
      beacon-node:
        - port: '{{ beacon_node_listening_port }}'
          protocol: 'tcp'
          disabled: '{{ not beacon_node_firewall_libp2p_open }}'
          comment: 'Beacon Node LibP2P'

        - port: '{{ beacon_node_discovery_port }}'
          protocol: 'udp'
          disabled: '{{ not beacon_node_firewall_libp2p_open }}'
          comment: 'Beacon Node Discovery'

        - port: '{{ beacon_node_metrics_port }}'
          iifname: 'wg0'
          ipset: 'metrics.hq'
          disabled: '{{ not beacon_node_firewall_metrics_open }}'
          comment: 'Beacon Node Metrics'

        - port: '{{ beacon_node_rest_port }}'
          iifname: 'wg0'
          ipset: '{{ env }}.{{ stage }}'
          comment: 'Beacon Node REST API'
