---
- name: Create systemd Unit file
  template:
    src: 'beacon-node.service.j2'
    dest: '/lib/systemd/system/{{ beacon_node_service_name }}.service'
    mode: 0644

- name: Reload systemctl
  command: systemctl daemon-reload

- name: Restart the service
  service:
    name: '{{ beacon_node_service_name }}.service'
    state: 'restarted'
    enabled: true
